// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPluginConfigHandlerFunc turns a function with the right signature into a get plugin config handler
type GetPluginConfigHandlerFunc func(GetPluginConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPluginConfigHandlerFunc) Handle(params GetPluginConfigParams) middleware.Responder {
	return fn(params)
}

// GetPluginConfigHandler interface for that can handle valid get plugin config params
type GetPluginConfigHandler interface {
	Handle(GetPluginConfigParams) middleware.Responder
}

// NewGetPluginConfig creates a new http.Handler for the get plugin config operation
func NewGetPluginConfig(ctx *middleware.Context, handler GetPluginConfigHandler) *GetPluginConfig {
	return &GetPluginConfig{Context: ctx, Handler: handler}
}

/*GetPluginConfig swagger:route GET /plugins/{pluginId}/config getPluginConfig

returns plugins specific settings object

*/
type GetPluginConfig struct {
	Context *middleware.Context
	Handler GetPluginConfigHandler
}

func (o *GetPluginConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPluginConfigParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
