// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/supergiant/robot/pkg/models"
)

// GetRecommendationPluginsOKCode is the HTTP code returned for type GetRecommendationPluginsOK
const GetRecommendationPluginsOKCode int = 200

/*GetRecommendationPluginsOK no error

swagger:response getRecommendationPluginsOK
*/
type GetRecommendationPluginsOK struct {

	/*
	  In: Body
	*/
	Payload *GetRecommendationPluginsOKBody `json:"body,omitempty"`
}

// NewGetRecommendationPluginsOK creates GetRecommendationPluginsOK with default headers values
func NewGetRecommendationPluginsOK() *GetRecommendationPluginsOK {

	return &GetRecommendationPluginsOK{}
}

// WithPayload adds the payload to the get recommendation plugins o k response
func (o *GetRecommendationPluginsOK) WithPayload(payload *GetRecommendationPluginsOKBody) *GetRecommendationPluginsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get recommendation plugins o k response
func (o *GetRecommendationPluginsOK) SetPayload(payload *GetRecommendationPluginsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRecommendationPluginsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRecommendationPluginsDefault error

swagger:response getRecommendationPluginsDefault
*/
type GetRecommendationPluginsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRecommendationPluginsDefault creates GetRecommendationPluginsDefault with default headers values
func NewGetRecommendationPluginsDefault(code int) *GetRecommendationPluginsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRecommendationPluginsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get recommendation plugins default response
func (o *GetRecommendationPluginsDefault) WithStatusCode(code int) *GetRecommendationPluginsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get recommendation plugins default response
func (o *GetRecommendationPluginsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get recommendation plugins default response
func (o *GetRecommendationPluginsDefault) WithPayload(payload *models.Error) *GetRecommendationPluginsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get recommendation plugins default response
func (o *GetRecommendationPluginsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRecommendationPluginsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
