// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPromethiusIntegrationInfoHandlerFunc turns a function with the right signature into a get promethius integration info handler
type GetPromethiusIntegrationInfoHandlerFunc func(GetPromethiusIntegrationInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPromethiusIntegrationInfoHandlerFunc) Handle(params GetPromethiusIntegrationInfoParams) middleware.Responder {
	return fn(params)
}

// GetPromethiusIntegrationInfoHandler interface for that can handle valid get promethius integration info params
type GetPromethiusIntegrationInfoHandler interface {
	Handle(GetPromethiusIntegrationInfoParams) middleware.Responder
}

// NewGetPromethiusIntegrationInfo creates a new http.Handler for the get promethius integration info operation
func NewGetPromethiusIntegrationInfo(ctx *middleware.Context, handler GetPromethiusIntegrationInfoHandler) *GetPromethiusIntegrationInfo {
	return &GetPromethiusIntegrationInfo{Context: ctx, Handler: handler}
}

/*GetPromethiusIntegrationInfo swagger:route GET /integration/prometheus getPromethiusIntegrationInfo

returns prometheus instance info and name of cluster

*/
type GetPromethiusIntegrationInfo struct {
	Context *middleware.Context
	Handler GetPromethiusIntegrationInfoHandler
}

func (o *GetPromethiusIntegrationInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPromethiusIntegrationInfoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
