// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/supergiant/analyze/pkg/models"
)

// GetPluginOKCode is the HTTP code returned for type GetPluginOK
const GetPluginOKCode int = 200

/*GetPluginOK no error

swagger:response getPluginOK
*/
type GetPluginOK struct {

	/*
	  In: Body
	*/
	Payload *models.Plugin `json:"body,omitempty"`
}

// NewGetPluginOK creates GetPluginOK with default headers values
func NewGetPluginOK() *GetPluginOK {

	return &GetPluginOK{}
}

// WithPayload adds the payload to the get plugin o k response
func (o *GetPluginOK) WithPayload(payload *models.Plugin) *GetPluginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plugin o k response
func (o *GetPluginOK) SetPayload(payload *models.Plugin) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPluginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPluginNotFoundCode is the HTTP code returned for type GetPluginNotFound
const GetPluginNotFoundCode int = 404

/*GetPluginNotFound Not Found

swagger:response getPluginNotFound
*/
type GetPluginNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPluginNotFound creates GetPluginNotFound with default headers values
func NewGetPluginNotFound() *GetPluginNotFound {

	return &GetPluginNotFound{}
}

// WithPayload adds the payload to the get plugin not found response
func (o *GetPluginNotFound) WithPayload(payload *models.Error) *GetPluginNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plugin not found response
func (o *GetPluginNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPluginNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPluginDefault error

swagger:response getPluginDefault
*/
type GetPluginDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPluginDefault creates GetPluginDefault with default headers values
func NewGetPluginDefault(code int) *GetPluginDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPluginDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get plugin default response
func (o *GetPluginDefault) WithStatusCode(code int) *GetPluginDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get plugin default response
func (o *GetPluginDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get plugin default response
func (o *GetPluginDefault) WithPayload(payload *models.Error) *GetPluginDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plugin default response
func (o *GetPluginDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPluginDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
