// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPromethiusIntegrationValidationsHandlerFunc turns a function with the right signature into a get promethius integration validations handler
type GetPromethiusIntegrationValidationsHandlerFunc func(GetPromethiusIntegrationValidationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPromethiusIntegrationValidationsHandlerFunc) Handle(params GetPromethiusIntegrationValidationsParams) middleware.Responder {
	return fn(params)
}

// GetPromethiusIntegrationValidationsHandler interface for that can handle valid get promethius integration validations params
type GetPromethiusIntegrationValidationsHandler interface {
	Handle(GetPromethiusIntegrationValidationsParams) middleware.Responder
}

// NewGetPromethiusIntegrationValidations creates a new http.Handler for the get promethius integration validations operation
func NewGetPromethiusIntegrationValidations(ctx *middleware.Context, handler GetPromethiusIntegrationValidationsHandler) *GetPromethiusIntegrationValidations {
	return &GetPromethiusIntegrationValidations{Context: ctx, Handler: handler}
}

/*GetPromethiusIntegrationValidations swagger:route GET /integration/prometheus/validations getPromethiusIntegrationValidations

returns list of integration validations

*/
type GetPromethiusIntegrationValidations struct {
	Context *middleware.Context
	Handler GetPromethiusIntegrationValidationsHandler
}

func (o *GetPromethiusIntegrationValidations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPromethiusIntegrationValidationsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
