// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UnregisterPluginHandlerFunc turns a function with the right signature into a unregister plugin handler
type UnregisterPluginHandlerFunc func(UnregisterPluginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UnregisterPluginHandlerFunc) Handle(params UnregisterPluginParams) middleware.Responder {
	return fn(params)
}

// UnregisterPluginHandler interface for that can handle valid unregister plugin params
type UnregisterPluginHandler interface {
	Handle(UnregisterPluginParams) middleware.Responder
}

// NewUnregisterPlugin creates a new http.Handler for the unregister plugin operation
func NewUnregisterPlugin(ctx *middleware.Context, handler UnregisterPluginHandler) *UnregisterPlugin {
	return &UnregisterPlugin{Context: ctx, Handler: handler}
}

/*UnregisterPlugin swagger:route DELETE /plugins/{pluginId} unregisterPlugin

unregisters plugin

*/
type UnregisterPlugin struct {
	Context *middleware.Context
	Handler UnregisterPluginHandler
}

func (o *UnregisterPlugin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUnregisterPluginParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
