// Code generated by go-swagger; DO NOT EDIT.

/*
Package api Analyze service API

    Schemes:
      http
    Host: localhost
    BasePath: /api/v1
    Version: v0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package api
