// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Analyze service API",
    "version": "v0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/check": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Returns list of check results produced by installed plugins",
        "operationId": "getCheckResults",
        "responses": {
          "200": {
            "description": "no error",
            "schema": {
              "description": "existing checks",
              "type": "array",
              "items": {
                "$ref": "#/definitions/checkResult"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/plugin": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Returns list of the installed recommendation plugins",
        "operationId": "getPlugins",
        "responses": {
          "200": {
            "description": "no error",
            "schema": {
              "type": "object",
              "properties": {
                "installedPlugins": {
                  "description": "installed plugins",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/plugin"
                  }
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "checkResult": {
      "description": "CheckResult represents the single result of Check function invocation of specific plugin.",
      "type": "object",
      "properties": {
        "checkStatus": {
          "description": "shows check status",
          "type": "string",
          "enum": [
            "RED",
            "YELLOW",
            "GREEN"
          ]
        },
        "completedAt": {
          "description": "date/Time of check execution",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "description": "detailed check result description",
          "type": "string"
        },
        "executionStatus": {
          "description": "shows check execution errors",
          "type": "string"
        },
        "id": {
          "description": "unique UUID of Check function invocation of specific plugin",
          "type": "string"
        },
        "name": {
          "description": "check name",
          "type": "string"
        },
        "possibleActions": {
          "description": "list of possible actions to fix caveats check was found",
          "type": "array",
          "items": {
            "$ref": "#/definitions/pluginAction"
          }
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "plugin": {
      "description": "plugin represents the installed recommendation plugin",
      "type": "object",
      "properties": {
        "description": {
          "description": "detailed plugin description",
          "type": "string"
        },
        "id": {
          "description": "unique ID of installed plugin\nbasically it is slugged URI of plugin repository name e. g. supergiant-request-limits-check\n",
          "type": "string"
        },
        "installedAt": {
          "description": "date/Time the plugin was installed",
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "description": "name is the name of the plugin.",
          "type": "string"
        },
        "status": {
          "description": "plugin status",
          "type": "string"
        },
        "version": {
          "description": "plugin version, major version shall be equal to robots version",
          "type": "string"
        }
      }
    },
    "pluginAction": {
      "description": "CheckResult represents the single result of Check function invocation of specific plugin.",
      "type": "object",
      "properties": {
        "description": {
          "description": "detailed action description",
          "type": "string"
        },
        "id": {
          "description": "unique UUID of plugin action",
          "type": "string"
        },
        "name": {
          "description": "name of plugin action",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Analyze service API",
    "version": "v0.0.1"
  },
  "basePath": "/api/v1",
  "paths": {
    "/check": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Returns list of check results produced by installed plugins",
        "operationId": "getCheckResults",
        "responses": {
          "200": {
            "description": "no error",
            "schema": {
              "description": "existing checks",
              "type": "array",
              "items": {
                "$ref": "#/definitions/checkResult"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/plugin": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Returns list of the installed recommendation plugins",
        "operationId": "getPlugins",
        "responses": {
          "200": {
            "description": "no error",
            "schema": {
              "type": "object",
              "properties": {
                "installedPlugins": {
                  "description": "installed plugins",
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/plugin"
                  }
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "checkResult": {
      "description": "CheckResult represents the single result of Check function invocation of specific plugin.",
      "type": "object",
      "properties": {
        "checkStatus": {
          "description": "shows check status",
          "type": "string",
          "enum": [
            "RED",
            "YELLOW",
            "GREEN"
          ]
        },
        "completedAt": {
          "description": "date/Time of check execution",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "description": "detailed check result description",
          "type": "string"
        },
        "executionStatus": {
          "description": "shows check execution errors",
          "type": "string"
        },
        "id": {
          "description": "unique UUID of Check function invocation of specific plugin",
          "type": "string"
        },
        "name": {
          "description": "check name",
          "type": "string"
        },
        "possibleActions": {
          "description": "list of possible actions to fix caveats check was found",
          "type": "array",
          "items": {
            "$ref": "#/definitions/pluginAction"
          }
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "plugin": {
      "description": "plugin represents the installed recommendation plugin",
      "type": "object",
      "properties": {
        "description": {
          "description": "detailed plugin description",
          "type": "string"
        },
        "id": {
          "description": "unique ID of installed plugin\nbasically it is slugged URI of plugin repository name e. g. supergiant-request-limits-check\n",
          "type": "string"
        },
        "installedAt": {
          "description": "date/Time the plugin was installed",
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "description": "name is the name of the plugin.",
          "type": "string"
        },
        "status": {
          "description": "plugin status",
          "type": "string"
        },
        "version": {
          "description": "plugin version, major version shall be equal to robots version",
          "type": "string"
        }
      }
    },
    "pluginAction": {
      "description": "CheckResult represents the single result of Check function invocation of specific plugin.",
      "type": "object",
      "properties": {
        "description": {
          "description": "detailed action description",
          "type": "string"
        },
        "id": {
          "description": "unique UUID of plugin action",
          "type": "string"
        },
        "name": {
          "description": "name of plugin action",
          "type": "string"
        }
      }
    }
  }
}`))
}
