// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/plugin.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CheckStatus int32

const (
	CheckStatus_UNKNOWN_CHECK_STATUS CheckStatus = 0
	CheckStatus_GREEN                CheckStatus = 1
	CheckStatus_YELLOW               CheckStatus = 2
	CheckStatus_RED                  CheckStatus = 3
)

var CheckStatus_name = map[int32]string{
	0: "UNKNOWN_CHECK_STATUS",
	1: "GREEN",
	2: "YELLOW",
	3: "RED",
}

var CheckStatus_value = map[string]int32{
	"UNKNOWN_CHECK_STATUS": 0,
	"GREEN":                1,
	"YELLOW":               2,
	"RED":                  3,
}

func (x CheckStatus) String() string {
	return proto.EnumName(CheckStatus_name, int32(x))
}

func (CheckStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{0}
}

type PluginInfo struct {
	//unique ID of plugin
	//basically it is slugged URI of plugin repository name e. g. supergiant-underutilized-nodes
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//plugin version in semver format
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	//short name of plugin
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// detailed plugin description
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginInfo) Reset()         { *m = PluginInfo{} }
func (m *PluginInfo) String() string { return proto.CompactTextString(m) }
func (*PluginInfo) ProtoMessage()    {}
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{0}
}

func (m *PluginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginInfo.Unmarshal(m, b)
}
func (m *PluginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginInfo.Marshal(b, m, deterministic)
}
func (m *PluginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginInfo.Merge(m, src)
}
func (m *PluginInfo) XXX_Size() int {
	return xxx_messageInfo_PluginInfo.Size(m)
}
func (m *PluginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PluginInfo proto.InternalMessageInfo

func (m *PluginInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PluginInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PluginInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type PluginConfig struct {
	CloudProviderType    string   `protobuf:"bytes,1,opt,name=cloud_provider_type,json=cloudProviderType,proto3" json:"cloud_provider_type,omitempty"`
	FinancialApiUri      string   `protobuf:"bytes,2,opt,name=financial_api_uri,json=financialApiUri,proto3" json:"financial_api_uri,omitempty"`
	ApiServerUri         string   `protobuf:"bytes,3,opt,name=api_server_uri,json=apiServerUri,proto3" json:"api_server_uri,omitempty"`
	MetricsUri           string   `protobuf:"bytes,4,opt,name=metrics_uri,json=metricsUri,proto3" json:"metrics_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginConfig) Reset()         { *m = PluginConfig{} }
func (m *PluginConfig) String() string { return proto.CompactTextString(m) }
func (*PluginConfig) ProtoMessage()    {}
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{1}
}

func (m *PluginConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginConfig.Unmarshal(m, b)
}
func (m *PluginConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginConfig.Marshal(b, m, deterministic)
}
func (m *PluginConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginConfig.Merge(m, src)
}
func (m *PluginConfig) XXX_Size() int {
	return xxx_messageInfo_PluginConfig.Size(m)
}
func (m *PluginConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PluginConfig proto.InternalMessageInfo

func (m *PluginConfig) GetCloudProviderType() string {
	if m != nil {
		return m.CloudProviderType
	}
	return ""
}

func (m *PluginConfig) GetFinancialApiUri() string {
	if m != nil {
		return m.FinancialApiUri
	}
	return ""
}

func (m *PluginConfig) GetApiServerUri() string {
	if m != nil {
		return m.ApiServerUri
	}
	return ""
}

func (m *PluginConfig) GetMetricsUri() string {
	if m != nil {
		return m.MetricsUri
	}
	return ""
}

type Stop struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop) Reset()         { *m = Stop{} }
func (m *Stop) String() string { return proto.CompactTextString(m) }
func (*Stop) ProtoMessage()    {}
func (*Stop) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{2}
}

func (m *Stop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop.Unmarshal(m, b)
}
func (m *Stop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop.Marshal(b, m, deterministic)
}
func (m *Stop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop.Merge(m, src)
}
func (m *Stop) XXX_Size() int {
	return xxx_messageInfo_Stop.Size(m)
}
func (m *Stop) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop.DiscardUnknown(m)
}

var xxx_messageInfo_Stop proto.InternalMessageInfo

type Stop_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop_Request) Reset()         { *m = Stop_Request{} }
func (m *Stop_Request) String() string { return proto.CompactTextString(m) }
func (*Stop_Request) ProtoMessage()    {}
func (*Stop_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{2, 0}
}

func (m *Stop_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop_Request.Unmarshal(m, b)
}
func (m *Stop_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop_Request.Marshal(b, m, deterministic)
}
func (m *Stop_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop_Request.Merge(m, src)
}
func (m *Stop_Request) XXX_Size() int {
	return xxx_messageInfo_Stop_Request.Size(m)
}
func (m *Stop_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Stop_Request proto.InternalMessageInfo

type Stop_Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stop_Response) Reset()         { *m = Stop_Response{} }
func (m *Stop_Response) String() string { return proto.CompactTextString(m) }
func (*Stop_Response) ProtoMessage()    {}
func (*Stop_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{2, 1}
}

func (m *Stop_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stop_Response.Unmarshal(m, b)
}
func (m *Stop_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stop_Response.Marshal(b, m, deterministic)
}
func (m *Stop_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stop_Response.Merge(m, src)
}
func (m *Stop_Response) XXX_Size() int {
	return xxx_messageInfo_Stop_Response.Size(m)
}
func (m *Stop_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Stop_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Stop_Response proto.InternalMessageInfo

func (m *Stop_Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{3}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

type CheckResponse struct {
	Result               *CheckResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error                string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{4}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetResult() *CheckResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CheckResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CheckResult struct {
	ExecutionStatus      string      `protobuf:"bytes,1,opt,name=execution_status,json=executionStatus,proto3" json:"execution_status,omitempty"`
	Status               CheckStatus `protobuf:"varint,2,opt,name=status,proto3,enum=proto.CheckStatus" json:"status,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Actions              []*Action   `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CheckResult) Reset()         { *m = CheckResult{} }
func (m *CheckResult) String() string { return proto.CompactTextString(m) }
func (*CheckResult) ProtoMessage()    {}
func (*CheckResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{5}
}

func (m *CheckResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResult.Unmarshal(m, b)
}
func (m *CheckResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResult.Marshal(b, m, deterministic)
}
func (m *CheckResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResult.Merge(m, src)
}
func (m *CheckResult) XXX_Size() int {
	return xxx_messageInfo_CheckResult.Size(m)
}
func (m *CheckResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResult proto.InternalMessageInfo

func (m *CheckResult) GetExecutionStatus() string {
	if m != nil {
		return m.ExecutionStatus
	}
	return ""
}

func (m *CheckResult) GetStatus() CheckStatus {
	if m != nil {
		return m.Status
	}
	return CheckStatus_UNKNOWN_CHECK_STATUS
}

func (m *CheckResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckResult) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CheckResult) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type Action struct {
	ActionId             string   `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{6}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *Action) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ActionRequest struct {
	ActionId             string   `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{7}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

type ActionResponse struct {
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionResponse) Reset()         { *m = ActionResponse{} }
func (m *ActionResponse) String() string { return proto.CompactTextString(m) }
func (*ActionResponse) ProtoMessage()    {}
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{8}
}

func (m *ActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionResponse.Unmarshal(m, b)
}
func (m *ActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionResponse.Marshal(b, m, deterministic)
}
func (m *ActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionResponse.Merge(m, src)
}
func (m *ActionResponse) XXX_Size() int {
	return xxx_messageInfo_ActionResponse.Size(m)
}
func (m *ActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActionResponse proto.InternalMessageInfo

func (m *ActionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{9}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("proto.CheckStatus", CheckStatus_name, CheckStatus_value)
	proto.RegisterType((*PluginInfo)(nil), "proto.PluginInfo")
	proto.RegisterType((*PluginConfig)(nil), "proto.PluginConfig")
	proto.RegisterType((*Stop)(nil), "proto.Stop")
	proto.RegisterType((*Stop_Request)(nil), "proto.Stop.Request")
	proto.RegisterType((*Stop_Response)(nil), "proto.Stop.Response")
	proto.RegisterType((*CheckRequest)(nil), "proto.CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "proto.CheckResponse")
	proto.RegisterType((*CheckResult)(nil), "proto.CheckResult")
	proto.RegisterType((*Action)(nil), "proto.Action")
	proto.RegisterType((*ActionRequest)(nil), "proto.ActionRequest")
	proto.RegisterType((*ActionResponse)(nil), "proto.ActionResponse")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto.RegisterFile("proto/plugin.proto", fileDescriptor_4368bc2f41172306) }

var fileDescriptor_4368bc2f41172306 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0xb5, 0x85, 0xc2, 0x72, 0x61, 0x59, 0x98, 0xc5, 0xa4, 0xc1, 0x07, 0x49, 0x63, 0xdc, 0x95,
	0x18, 0x8c, 0x6c, 0xfc, 0x00, 0x82, 0x0d, 0x6e, 0x76, 0xc3, 0xae, 0x05, 0xb2, 0xf1, 0xa9, 0xa9,
	0xed, 0xb0, 0x4e, 0x2c, 0xed, 0x38, 0x33, 0x25, 0xf2, 0x59, 0x7e, 0x83, 0x1f, 0xa6, 0xe9, 0xcc,
	0x50, 0xa1, 0x26, 0x3e, 0xf8, 0xd4, 0xb9, 0xe7, 0x9e, 0x3b, 0xe7, 0xf6, 0xcc, 0xbd, 0x80, 0x28,
	0x4b, 0x45, 0xfa, 0x86, 0xc6, 0xd9, 0x23, 0x49, 0x46, 0x32, 0x40, 0x96, 0xfc, 0x38, 0x31, 0xc0,
	0xbd, 0x84, 0xaf, 0x93, 0x75, 0x8a, 0xda, 0x60, 0x92, 0xc8, 0x36, 0x06, 0xc6, 0x65, 0xc3, 0x33,
	0x49, 0x84, 0x6c, 0xa8, 0x6f, 0x31, 0xe3, 0x24, 0x4d, 0x6c, 0x53, 0x82, 0xfb, 0x10, 0x21, 0xa8,
	0x26, 0xc1, 0x06, 0xdb, 0x15, 0x09, 0xcb, 0x33, 0x1a, 0x40, 0x33, 0xc2, 0x3c, 0x64, 0x84, 0x8a,
	0xbc, 0xa2, 0x2a, 0x53, 0x87, 0x90, 0xf3, 0xc3, 0x80, 0x96, 0x92, 0x9b, 0xa6, 0xc9, 0x9a, 0x3c,
	0xa2, 0x11, 0x9c, 0x87, 0x71, 0x9a, 0x45, 0x3e, 0x65, 0xe9, 0x96, 0x44, 0x98, 0xf9, 0x62, 0x47,
	0xb1, 0xee, 0xa0, 0x2b, 0x53, 0xf7, 0x3a, 0xb3, 0xdc, 0x51, 0x8c, 0x86, 0xd0, 0x5d, 0x93, 0x24,
	0x48, 0x42, 0x12, 0xc4, 0x7e, 0x40, 0x89, 0x9f, 0x31, 0xa2, 0x5b, 0x3b, 0x2b, 0x12, 0x13, 0x4a,
	0x56, 0x8c, 0xa0, 0x17, 0xd0, 0xce, 0x19, 0x1c, 0xb3, 0x2d, 0x66, 0x92, 0xa8, 0x9a, 0x6d, 0x05,
	0x94, 0x2c, 0x24, 0x98, 0xb3, 0x9e, 0x43, 0x73, 0x83, 0x05, 0x23, 0x21, 0x97, 0x14, 0xd5, 0x34,
	0x68, 0x68, 0xc5, 0x88, 0x73, 0x05, 0xd5, 0x85, 0x48, 0x69, 0xbf, 0x01, 0x75, 0x0f, 0x7f, 0xcb,
	0x30, 0x17, 0xfd, 0x01, 0x9c, 0x78, 0x98, 0xd3, 0x34, 0xe1, 0x18, 0xf5, 0xc0, 0xc2, 0x8c, 0xa5,
	0x4c, 0xf7, 0xac, 0x02, 0xa7, 0x0d, 0xad, 0xe9, 0x17, 0x1c, 0x7e, 0xd5, 0x15, 0xce, 0x47, 0x38,
	0xd5, 0xb1, 0x2e, 0x1b, 0x42, 0x8d, 0x61, 0x9e, 0xc5, 0x42, 0xd6, 0x35, 0xc7, 0x48, 0x3d, 0xcb,
	0x68, 0xcf, 0xca, 0x62, 0xe1, 0x69, 0xc6, 0x1f, 0x09, 0xf3, 0x50, 0xe2, 0xa7, 0x01, 0xcd, 0x03,
	0x36, 0x7a, 0x05, 0x1d, 0xfc, 0x1d, 0x87, 0x59, 0x6e, 0xb4, 0xcf, 0x45, 0x20, 0x32, 0xae, 0x7b,
	0x3a, 0x2b, 0xf0, 0x85, 0x84, 0x73, 0x71, 0x4d, 0xc8, 0x6f, 0x6c, 0x1f, 0x8b, 0x2b, 0x8e, 0xa7,
	0x19, 0xff, 0xf7, 0xd0, 0xe8, 0x02, 0xea, 0x41, 0x98, 0x9f, 0xb8, 0x6d, 0x0d, 0x2a, 0x97, 0xcd,
	0xf1, 0xa9, 0x96, 0x98, 0x48, 0xd4, 0xdb, 0x67, 0x9d, 0x19, 0xd4, 0x14, 0x84, 0x9e, 0x41, 0x43,
	0x81, 0x7e, 0x31, 0x82, 0x27, 0x0a, 0xb8, 0x8e, 0xca, 0x8a, 0xe6, 0xdf, 0xa3, 0xf5, 0x1a, 0x4e,
	0xf5, 0xdd, 0xca, 0xf2, 0x7f, 0xde, 0xe7, 0xbc, 0x84, 0xf6, 0x9e, 0x5d, 0x7e, 0xc7, 0x23, 0x93,
	0xeb, 0x60, 0xb9, 0x1b, 0x2a, 0x76, 0xc3, 0x99, 0x36, 0x5b, 0x3b, 0x68, 0x43, 0x6f, 0x35, 0xbf,
	0x99, 0xdf, 0x3d, 0xcc, 0xfd, 0xe9, 0x07, 0x77, 0x7a, 0xe3, 0x2f, 0x96, 0x93, 0xe5, 0x6a, 0xd1,
	0x79, 0x82, 0x1a, 0x60, 0xcd, 0x3c, 0xd7, 0x9d, 0x77, 0x0c, 0x04, 0x50, 0xfb, 0xe4, 0xde, 0xde,
	0xde, 0x3d, 0x74, 0x4c, 0x54, 0x87, 0x8a, 0xe7, 0xbe, 0xef, 0x54, 0xc6, 0xbf, 0x0c, 0xa8, 0xa9,
	0x15, 0x40, 0x17, 0x50, 0x95, 0x5b, 0xd7, 0xd2, 0xde, 0x48, 0xa5, 0x7e, 0x57, 0x47, 0x07, 0x6b,
	0x39, 0x06, 0x4b, 0x8a, 0xa3, 0xf3, 0xe3, 0x29, 0x51, 0xd3, 0xd8, 0x2b, 0x8d, 0x8e, 0xfa, 0x9f,
	0x77, 0x85, 0xb1, 0xbd, 0x63, 0xeb, 0x75, 0xd5, 0xd3, 0x12, 0xaa, 0xcb, 0x46, 0xd0, 0x50, 0xab,
	0x99, 0x31, 0x5c, 0xc8, 0x1d, 0xae, 0x6c, 0xff, 0xa8, 0x5b, 0xf4, 0x56, 0x6d, 0x47, 0x41, 0xcd,
	0x83, 0x51, 0xb9, 0x33, 0x0d, 0x2a, 0x89, 0xcf, 0x35, 0x09, 0x5e, 0xfd, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0xd6, 0xeb, 0x90, 0x96, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	Configure(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (*Empty, error)
	//Graceful Shutdown Plugin
	Stop(ctx context.Context, in *Stop_Request, opts ...grpc.CallOption) (*Stop_Response, error)
}

type pluginClient struct {
	cc *grpc.ClientConn
}

func NewPluginClient(cc *grpc.ClientConn) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Configure(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Stop(ctx context.Context, in *Stop_Request, opts ...grpc.CallOption) (*Stop_Response, error) {
	out := new(Stop_Response)
	err := c.cc.Invoke(ctx, "/proto.Plugin/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	Info(context.Context, *Empty) (*PluginInfo, error)
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	Action(context.Context, *ActionRequest) (*ActionResponse, error)
	Configure(context.Context, *PluginConfig) (*Empty, error)
	//Graceful Shutdown Plugin
	Stop(context.Context, *Stop_Request) (*Stop_Response, error)
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Configure(ctx, req.(*PluginConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stop_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Plugin/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Stop(ctx, req.(*Stop_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Plugin_Info_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Plugin_Check_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _Plugin_Action_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Plugin_Configure_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Plugin_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin.proto",
}
