// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PluginAction CheckResult represents the single result of Check function invocation of specific plugin.
// swagger:model pluginAction
type PluginAction struct {

	// detailed action description
	Description string `json:"description,omitempty"`

	// unique UUID of plugin action
	ID string `json:"id,omitempty"`

	// name of plugin action
	Name string `json:"name,omitempty"`
}

// Validate validates this plugin action
func (m *PluginAction) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PluginAction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PluginAction) UnmarshalBinary(b []byte) error {
	var res PluginAction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
