// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// RecommendationPlugin RecommendationPlugin represents the installed recommendation plugin
// swagger:model RecommendationPlugin
type RecommendationPlugin struct {

	// detailed plugin description
	Description string `json:"Description,omitempty"`

	// unique ID of installed plugin
	// basically it is slugged URI of plugin repository name e. g. supergiant-request-limits-check
	//
	ID string `json:"Id,omitempty"`

	// date/Time the plugin was installed
	InstalledAt string `json:"InstalledAt,omitempty"`

	// name is the name of the plugin.
	Name string `json:"Name,omitempty"`

	// plugin status
	Status string `json:"Status,omitempty"`

	// plugin version, major version shall be equal to robots version
	Version string `json:"Version,omitempty"`
}

// Validate validates this recommendation plugin
func (m *RecommendationPlugin) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RecommendationPlugin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecommendationPlugin) UnmarshalBinary(b []byte) error {
	var res RecommendationPlugin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
