// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Validation single integration validation for component
// swagger:model validation
type Validation struct {

	// name of validation, e. g. node_exporter deamonSet is OK
	Name string `json:"name,omitempty"`

	// shows validation status
	// Enum: [OK FAILED]
	Status string `json:"status,omitempty"`
}

// Validate validates this validation
func (m *Validation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var validationTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["OK","FAILED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		validationTypeStatusPropEnum = append(validationTypeStatusPropEnum, v)
	}
}

const (

	// ValidationStatusOK captures enum value "OK"
	ValidationStatusOK string = "OK"

	// ValidationStatusFAILED captures enum value "FAILED"
	ValidationStatusFAILED string = "FAILED"
)

// prop value enum
func (m *Validation) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, validationTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Validation) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Validation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Validation) UnmarshalBinary(b []byte) error {
	var res Validation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
